[project]
name = "odoo-addons-oca-account-invoicing"
version = "19.0.20260108.0"
dependencies = [
    "odoo-addon-account_invoice_fixed_discount==19.0.*",
    "odoo-addon-account_invoice_pricelist==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
